baseURL = "https://symkowick.org/"
languageCode = "en-us"
theme = "hello-friend-ng"
pygmentsUseClasses = true

title = "Anthony Symkowick"
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
identifier = "gospel"
name = "Gospel"
url = "/top-level-pages/gospel"
weight = 3

[params]
contentTypeName = "posts"
description = "Personal website & blog of Anthony Symkowick."
homeSubtitle = "anthony symkowick"
images = [""]
keywords = ''' anthony symkowick, anthony, symkowick, blog, software, javascript,
development, programming, small web, ethical development '''

[taxonomies]
category = "categories"
tag = "tags"

# Enable raw <HTML> tags in markdown
[markup.goldmark.renderer]
unsafe=true
