baseURL = "https://symkowick.org/"
relativeUrls = true
languageCode = "en-us"
pygmentsUseClasses = true

theme = "ant_theme"

title = "ant's blog"
[[menu.main]]
identifier = "home"
name = "home"
url = "/"
weight = 1

[[menu.main]]
identifier = "blog"
name = "posts"
url = "/posts"
weight = 2

[[menu.main]]
identifier = "music"
name = "music"
url = "/music"
weight= 3

[[menu.main]]
identifier = "programming tips"
name = "programming tips"
url = "/gospel"
weight = 4

[params]
contentTypeName = "posts"
description = "Personal website & blog of Anthony Symkowick."
homeSubtitle = "anthony symkowick"
images = [""]
keywords = ''' anthony symkowick, anthony, symkowick, engineer, software engineering blog, software, javascript, flutter, dart,
development, programming, small web, ethical development '''

[taxonomies]
category = "categories"
tag = "tags"

# Enable raw <HTML> tags in markdown
[markup.goldmark.renderer]
unsafe=true
