baseURL = "https://symkowick.org/"
languageCode = "en-us"
theme = "hello-friend-ng"
pygmentsUseClasses = true

title = "Anthony Symkowick"
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
identifier = "covid"
name = "COVID-19 Data"
url = "https://www.flattenthecurve.com/"
weight = 3

[params]
contentTypeName = "posts"
description = "Personal website & blog of Anthony Symkowick."
homeSubtitle = "software developer - currently available for hire"
images = [""]
keywords = "anthony, symkowick, blog, software, javascript, development, programming"

[taxonomies]
category = "categories"
tag = "tags"
