PygmentsStyle = "dracula"
baseURL = "http://symkowick.org/"
languageCode = "en-us"
theme = "hello-friend-ng"

title = "Anthony Symkowick"
[[menu.main]]
identifier = "covid"
name = "COVID-19 Data"
url = "https://www.flattenthecurve.com/"
weight = 1

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"
weight = 2

[params]
contentTypeName = "posts"
description = "Personal website & blog of Anthony Symkowick."
homeSubtitle = "Hi! I'm a software developer currently available for hire!"
images = [""]
keywords = "anthony, symkowick, blog, software, javascript, development, programming"

[taxonomies]
category = "categories"
tag = "tags"
